# Generated by Django 4.0 on 2021-12-12 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512)),
                ('a', models.CharField(max_length=128)),
                ('b', models.CharField(max_length=128)),
                ('c', models.CharField(max_length=128)),
                ('d', models.CharField(max_length=128)),
                ('answer', models.CharField(choices=[('a', 'a'), ('b', 'b'), ('c', 'c'), ('d', 'd')], max_length=1)),
            ],
        ),
    ]
