# Generated by Django 4.0 on 2021-12-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('qcm', 'qcm'), ('cash', 'cash')], default='qcm', max_length=16),
            preserve_default=False,
        ),
    ]
