# Generated by Django 4.0 on 2021-12-12 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='c',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='d',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
