# Generated by Django 4.0 on 2021-12-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_question_question_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswered',
            name='user_answer',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
