# Generated by Django 4.0 on 2021-12-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_questionanswered_user_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='emoji',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
    ]
