# Generated by Django 4.0 on 2021-12-29 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_tag_emoji'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='emoji',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
