# Generated by Django 4.0 on 2021-12-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_questionanswered_question_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionanswered',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
