name: DockerCICD
on: [push]
jobs:

  Docker:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - 
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}"
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1

        with:
          username: swerdeste
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true 
          tags: swerdeste/thedataquiz:latest

  Deploy:
    runs-on: ubuntu-latest
    steps:      
      - name: Login
        uses: google-github-actions/setup-gcloud@v0.2.0 
        with:
          project_id: "moonlit-palace-338110"
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker ps
        run: |-
          gcloud --quiet beta compute ssh --zone "europe-west1-b" "quiz-app" --project "moonlit-palace-338110"
          docker ps
