name: DockerCICD
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Set up Docker Build
        uses: docker/setup-buildx-action@v1
      - 
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }}
      -
        name: Login to Docker Hub
        uses: docker/login-action@v1

        with:
          username: swerdeste
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
        
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true 


